@php
$selected = $selected ?? '+91';
@endphp

<option {{ $selected == '+1' ? 'selected' : '' }} value="+1">+1</option>
<option {{ $selected == '+7' ? 'selected' : '' }} value="+7">+7</option>
<option {{ $selected == '+20' ? 'selected' : '' }} value="+20">+20</option>
<option {{ $selected == '+27' ? 'selected' : '' }} value="+27">+27</option>
<option {{ $selected == '+30' ? 'selected' : '' }} value="+30">+30</option>
<option {{ $selected == '+31' ? 'selected' : '' }} value="+31">+31</option>
<option {{ $selected == '+32' ? 'selected' : '' }} value="+32">+32</option>
<option {{ $selected == '+33' ? 'selected' : '' }} value="+33">+33</option>
<option {{ $selected == '+34' ? 'selected' : '' }} value="+34">+34</option>
<option {{ $selected == '+36' ? 'selected' : '' }} value="+36">+36</option>
<option {{ $selected == '+39' ? 'selected' : '' }} value="+39">+39</option>
<option {{ $selected == '+40' ? 'selected' : '' }} value="+40">+40</option>
<option {{ $selected == '+41' ? 'selected' : '' }} value="+41">+41</option>
<option {{ $selected == '+43' ? 'selected' : '' }} value="+43">+43</option>
<option {{ $selected == '+44' ? 'selected' : '' }} value="+44">+44</option>
<option {{ $selected == '+45' ? 'selected' : '' }} value="+45">+45</option>
<option {{ $selected == '+46' ? 'selected' : '' }} value="+46">+46</option>
<option {{ $selected == '+47' ? 'selected' : '' }} value="+47">+47</option>
<option {{ $selected == '+48' ? 'selected' : '' }} value="+48">+48</option>
<option {{ $selected == '+49' ? 'selected' : '' }} value="+49">+49</option>
<option {{ $selected == '+51' ? 'selected' : '' }} value="+51">+51</option>
<option {{ $selected == '+52' ? 'selected' : '' }} value="+52">+52</option>
<option {{ $selected == '+53' ? 'selected' : '' }} value="+53">+53</option>
<option {{ $selected == '+54' ? 'selected' : '' }} value="+54">+54</option>
<option {{ $selected == '+55' ? 'selected' : '' }} value="+55">+55</option>
<option {{ $selected == '+56' ? 'selected' : '' }} value="+56">+56</option>
<option {{ $selected == '+57' ? 'selected' : '' }} value="+57">+57</option>
<option {{ $selected == '+58' ? 'selected' : '' }} value="+58">+58</option>
<option {{ $selected == '+60' ? 'selected' : '' }} value="+60">+60</option>
<option {{ $selected == '+61' ? 'selected' : '' }} value="+61">+61</option>
<option {{ $selected == '+62' ? 'selected' : '' }} value="+62">+62</option>
<option {{ $selected == '+63' ? 'selected' : '' }} value="+63">+63</option>
<option {{ $selected == '+64' ? 'selected' : '' }} value="+64">+64</option>
<option {{ $selected == '+65' ? 'selected' : '' }} value="+65">+65</option>
<option {{ $selected == '+66' ? 'selected' : '' }} value="+66">+66</option>
<option {{ $selected == '+81' ? 'selected' : '' }} value="+81">+81</option>
<option {{ $selected == '+82' ? 'selected' : '' }} value="+82">+82</option>
<option {{ $selected == '+84' ? 'selected' : '' }} value="+84">+84</option>
<option {{ $selected == '+86' ? 'selected' : '' }} value="+86">+86</option>
<option {{ $selected == '+90' ? 'selected' : '' }} value="+90">+90</option>
<option {{ $selected == '+91' ? 'selected' : '' }} value="+91">+91</option>
<option {{ $selected == '+92' ? 'selected' : '' }} value="+92">+92</option>
<option {{ $selected == '+93' ? 'selected' : '' }} value="+93">+93</option>
<option {{ $selected == '+94' ? 'selected' : '' }} value="+94">+94</option>
<option {{ $selected == '+95' ? 'selected' : '' }} value="+95">+95</option>
<option {{ $selected == '+98' ? 'selected' : '' }} value="+98">+98</option>
<option {{ $selected == '+211' ? 'selected' : '' }} value="+211">+211</option>
<option {{ $selected == '+212' ? 'selected' : '' }} value="+212">+212</option>
<option {{ $selected == '+213' ? 'selected' : '' }} value="+213">+213</option>
<option {{ $selected == '+216' ? 'selected' : '' }} value="+216">+216</option>
<option {{ $selected == '+218' ? 'selected' : '' }} value="+218">+218</option>
<option {{ $selected == '+220' ? 'selected' : '' }} value="+220">+220</option>
<option {{ $selected == '+221' ? 'selected' : '' }} value="+221">+221</option>
<option {{ $selected == '+222' ? 'selected' : '' }} value="+222">+222</option>
<option {{ $selected == '+223' ? 'selected' : '' }} value="+223">+223</option>
<option {{ $selected == '+224' ? 'selected' : '' }} value="+224">+224</option>
<option {{ $selected == '+225' ? 'selected' : '' }} value="+225">+225</option>
<option {{ $selected == '+226' ? 'selected' : '' }} value="+226">+226</option>
<option {{ $selected == '+227' ? 'selected' : '' }} value="+227">+227</option>
<option {{ $selected == '+228' ? 'selected' : '' }} value="+228">+228</option>
<option {{ $selected == '+229' ? 'selected' : '' }} value="+229">+229</option>
<option {{ $selected == '+230' ? 'selected' : '' }} value="+230">+230</option>
<option {{ $selected == '+231' ? 'selected' : '' }} value="+231">+231</option>
<option {{ $selected == '+232' ? 'selected' : '' }} value="+232">+232</option>
<option {{ $selected == '+233' ? 'selected' : '' }} value="+233">+233</option>
<option {{ $selected == '+234' ? 'selected' : '' }} value="+234">+234</option>
<option {{ $selected == '+235' ? 'selected' : '' }} value="+235">+235</option>
<option {{ $selected == '+236' ? 'selected' : '' }} value="+236">+236</option>
<option {{ $selected == '+237' ? 'selected' : '' }} value="+237">+237</option>
<option {{ $selected == '+238' ? 'selected' : '' }} value="+238">+238</option>
<option {{ $selected == '+239' ? 'selected' : '' }} value="+239">+239</option>
<option {{ $selected == '+240' ? 'selected' : '' }} value="+240">+240</option>
<option {{ $selected == '+241' ? 'selected' : '' }} value="+241">+241</option>
<option {{ $selected == '+242' ? 'selected' : '' }} value="+242">+242</option>
<option {{ $selected == '+243' ? 'selected' : '' }} value="+243">+243</option>
<option {{ $selected == '+244' ? 'selected' : '' }} value="+244">+244</option>
<option {{ $selected == '+245' ? 'selected' : '' }} value="+245">+245</option>
<option {{ $selected == '+246' ? 'selected' : '' }} value="+246">+246</option>
<option {{ $selected == '+247' ? 'selected' : '' }} value="+247">+247</option>
<option {{ $selected == '+248' ? 'selected' : '' }} value="+248">+248</option>
<option {{ $selected == '+249' ? 'selected' : '' }} value="+249">+249</option>
<option {{ $selected == '+250' ? 'selected' : '' }} value="+250">+250</option>
<option {{ $selected == '+251' ? 'selected' : '' }} value="+251">+251</option>
<option {{ $selected == '+252' ? 'selected' : '' }} value="+252">+252</option>
<option {{ $selected == '+253' ? 'selected' : '' }} value="+253">+253</option>
<option {{ $selected == '+254' ? 'selected' : '' }} value="+254">+254</option>
<option {{ $selected == '+255' ? 'selected' : '' }} value="+255">+255</option>
<option {{ $selected == '+256' ? 'selected' : '' }} value="+256">+256</option>
<option {{ $selected == '+257' ? 'selected' : '' }} value="+257">+257</option>
<option {{ $selected == '+258' ? 'selected' : '' }} value="+258">+258</option>
<option {{ $selected == '+260' ? 'selected' : '' }} value="+260">+260</option>
<option {{ $selected == '+261' ? 'selected' : '' }} value="+261">+261</option>
<option {{ $selected == '+262' ? 'selected' : '' }} value="+262">+262</option>
<option {{ $selected == '+263' ? 'selected' : '' }} value="+263">+263</option>
<option {{ $selected == '+264' ? 'selected' : '' }} value="+264">+264</option>
<option {{ $selected == '+265' ? 'selected' : '' }} value="+265">+265</option>
<option {{ $selected == '+266' ? 'selected' : '' }} value="+266">+266</option>
<option {{ $selected == '+267' ? 'selected' : '' }} value="+267">+267</option>
<option {{ $selected == '+268' ? 'selected' : '' }} value="+268">+268</option>
<option {{ $selected == '+269' ? 'selected' : '' }} value="+269">+269</option>
<option {{ $selected == '+290' ? 'selected' : '' }} value="+290">+290</option>
<option {{ $selected == '+291' ? 'selected' : '' }} value="+291">+291</option>
<option {{ $selected == '+297' ? 'selected' : '' }} value="+297">+297</option>
<option {{ $selected == '+298' ? 'selected' : '' }} value="+298">+298</option>
<option {{ $selected == '+299' ? 'selected' : '' }} value="+299">+299</option>
<option {{ $selected == '+353' ? 'selected' : '' }} value="+353">+353</option>
<option {{ $selected == '+358' ? 'selected' : '' }} value="+353">+358</option>